version: '3.8'

services:
  test-web-server:
    image: nginx:alpine
    container_name: aisim-test-server
    ports:
      - "8080:80"
    volumes:
      - ./test-websites:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - aisim-test-network

  selenium-chrome:
    image: selenium/standalone-chrome:latest
    container_name: aisim-test-chrome
    ports:
      - "4444:4444"
      - "7900:7900" # VNC server for visual debugging
    shm_size: 2gb
    networks:
      - aisim-test-network
    environment:
      - SE_VNC_NO_PASSWORD=1

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: aisim-test-runner
    depends_on:
      - test-web-server
      - selenium-chrome
    volumes:
      - ./tests:/app/tests
      - ./results:/app/results
    networks:
      - aisim-test-network
    environment:
      - SELENIUM_URL=http://selenium-chrome:4444
      - TEST_URL=http://test-web-server

networks:
  aisim-test-network:
    driver: bridge



